# Disk partition layout for ArchLike UEFI Installer with f2fs root

# Check for commands needed to accomplish the specified disk layout
checkcmd:
  - mkfs.vfat
  - mkfs.f2fs

# Helper tools to install on guest for specified filesystems
packages:
  install:
    - dosfstools
    - f2fs-tools

# Partition layout, filesystems, and mount data
partitions:
  part1:
    partinfo:
      partnum: 1
      label: "ARCHLIKE_BOOT"
      type: "esp"
      fs: "vfat"
      offsets:
        start: "0"
        end: "+512M"

    mountopts:
      path: "/efi"
      flags: "defaults"
      backup: 0
      check: 2

  part2:
    partinfo:
      partnum: 2
      label: "ARCHLIKE_ROOT"
      type: "root"
      fs: "f2fs"
      offsets:
        start: "0"
        end: "0"

    mountopts:
      path: "/"
      flags: "defaults"
      backup: 0
      check: 1
